

export enum ActionTypes {

    INITIALIZE_APP='INITIALIZE_APP',
    LOGIN = 'LOGIN',
    INITIALIZE_USER      = 'INITIALIZE_USER',
    REGISTRATION = 'REGISTRATION',
    LOGOUT='LOGOUT',
    SET_CURRENT_IMAGE='SET_CURRENT_IMAGE',
    SET_FAVOURITES='SET_FAVOURITES',
    
}