

export enum MutationTypes {
    
    INITIALIZE='INITIALIZE',
    SET_USER_CREDENTIALS = 'SET_USER_CREDENTIALS',
    SET_CURRENT_BOT      = 'SET_CURRENT_BOT',
    SET_USER_INITIAL_CREDENTIALS = 'SET_USER_INITIAL_CREDENTIALS',
    SET_CURRENT_IMAGE = 'SET_CURRENT_IMAGE',
    SET_FAVOURITES='SET_FAVOURITES'
}